config/routes.rb
Rails.application.routes.draw do
  resources :teams
  get "/calender", to: "calender#index"
  get "/search", to: "search#index"
  get "/read_notifications", to: "read_notifications#read_all"
  devise_for :users
  resources :dashboard, only: [:index]
  authenticate :user, ->(user) { user.organisation_owner? } do
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    resources :organisation_users do
      member do
        post "/change_roles", to: "organisation_users#change_role"
      end
    end
  end
  
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
    namespace :admin do
      resources :dashboard
    end
  end

  resources :notifications, only: [:index]
  resources :projects do
    resources :tasks
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    @organisation = Organisation.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.all
    @tasks = Task.all
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_admin_navbar.html.erb
<nav class="bg-gray-700 px-6 py-4 text-gray-200 flex items-center justify-between ">
  <div>
    <button data-action="click->toggle#toggleSidebar">
      <%= inline_svg_tag("sidebar.svg") %>
    </button>
  </div>
  <%= form_with url: search_path, method: :get, data: {controller: "search"} do |form| %>
    <div class="flex items-center relative">
      <%= form.text_field :name, class: "rounded-md bg-gray-700", placeholder: "Search For Products", data: {search_target: "input", action: "input->search#debounce"} %>
      <button type="submit" class="absolute right-0 cursor-pointer">
        <%= inline_svg_tag("search.svg") %>
      </button>
    </div>
  <% end %>
  <div data-action="click->toggle#toggleNotificationCard" class="relative cursor-pointer">
    <% if current_user.notifications.unread.any? %>
      <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-sky-400 opacity-75"></span>
    <% end %>
    <%= inline_svg_tag("notification.svg") %>
    <%= render 'dashboard/notification_card' %>
  </div>
  <div data-action="click->toggle#toggleProfileCard" class="relative cursor-pointer">
    <%= inline_svg_tag("user.svg") %>
    <%= render 'dashboard/profile_card' %>
  </div>
</nav>

app/views/dashboard/_cards.html.erb
<div class="flex gap-6 flex-wrap">
  <div class="p-4 rounded-lg bg-gray-600 h-24 min-w-24 text-center">
    <p class="capitalize mb-3 border-gray-800 rounded-md">Total Projects</p>
    <p class="font-bold bg-gray-800 rounded-md"><%= @projects.size %></p>
  </div>
  <div class="p-4 rounded-lg bg-gray-600 h-24 min-w-24 text-center">
    <p class="capitalize mb-3 border-gray-800 rounded-md">Total Tasks</p>
    <p class="font-bold bg-gray-800 rounded-md"><%= @tasks.size %></p>
  </div>
  <div class="p-4 rounded-lg bg-gray-600 h-24 min-w-24 text-center">
    <p class="capitalize mb-3 border-gray-800 rounded-md">Urgent Tasks</p>
    <p class="font-bold bg-gray-800 rounded-md"><%= @tasks.urgent.size %></p>
  </div>
  <div class="p-4 rounded-lg bg-gray-600 h-24 min-w-24 text-center">
    <p class="capitalize mb-3 border-gray-800 rounded-md">Completed Tasks</p>
    <p class="font-bold bg-gray-800 rounded-md"><%= @tasks.completed.size %></p>
  </div>
  <div class="p-4 rounded-lg bg-gray-600 h-24 min-w-24 text-center">
    <p class="capitalize mb-3 border-gray-800 rounded-md">Expired Tasks</p>
    <p class="font-bold bg-gray-800 rounded-md"><%= @tasks.expired.size %></p>
  </div>
  <div class="p-4 rounded-lg bg-gray-600 h-24 min-w-24 text-center">
    <p class="capitalize mb-3 border-gray-800 rounded-md">Pending Projects</p>
    <p class="font-bold bg-gray-800 rounded-md"><%= @tasks.pending.size %></p>
  </div>
</div>

app/views/dashboard/_charts.html.erb
<div class="mt-6 grid text-center md:flex gap-6 md:justify-around">
  <div class="rounded-md bg-gray-300 p-2 mt-3">
    <h2 class="text-gray-900">Task by priority</h2>
    <%= pie_chart @tasks.group(:priority).count %>
  </div>
  <div class="rounded-md bg-gray-300 p-2 mt-3">
    <h2 class="text-gray-900 capitalize">Task by due date</h2>
    <%= line_chart @tasks.group_by_day(:due_date).count %>
  </div>
</div>

app/views/dashboard/_main.html.erb
<main class="p-3 text-gray-200 mx-auto">
  <%= render "cards" %>
  <%= render 'charts' %>
</main>

app/views/dashboard/_notification_card.html.erb
<div data-toggle-target="notificationCard" class="hidden rounded-md font-semibold capitalize bg-gray-600 w-96 h-fit p-4 absolute right-0 mt-4">
  <ul>
    <% current_user.notifications.unread.limit(5).each do |notification| %>
      <li class="mb-6">
        <%= link_to notification.message, notifications_path %>
      </li>
    <% end %>
    <% if current_user.notifications.unread.any? %>
      <li class="mb-6 bg-gray-900 rounded-md p-2"><%= link_to "See all", notifications_path %></li>
    <% else %>
      <li class="mb-6 bg-gray-900 rounded-md p-2"></li>
    <% end %>
  </ul>
</div>

app/views/dashboard/_profile_card.html.erb
<div data-toggle-target="profileCard" class="hidden rounded-md font-semibold capitalize bg-gray-600 size-32 p-4 absolute right-0 mt-4">
  <ul>
    <li class="mb-4"><%= link_to "Profile", edit_user_registration_path %></li>
    <li><%= button_to "Logout", destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

app/views/dashboard/_sidebar.html.erb
<aside data-toggle-target="sidebar" class="fixed h-screen hidden bg-gray-700 w-32 text-gray-200 pl-6 font-bold capitalize">
  <ul>
    <li class="mt-6">
      <a href="#" class="hover:text-gray-800">Home</a>
    </li>
    <li class="mt-6">
      <a href="/dashboard" class="hover:text-gray-800">Dashboard</a>
    </li>
    <li class="mt-6">
      <a href="/projects">Project</a>
    </li>
    <li class="mt-6">
      <a href="/calender">Calender</a>
    </li>
    <% if current_user.organisation_owner? %>
      <li class="mt-6">
        <a href="/organisation_users">Users</a>
      </li>
    <% end %>
    <li class="mt-6">
      <a href="/teams">Teams</a>
    </li>
  </ul>
</aside>

app/views/dashboard/index.html.erb
<div data-controller="toggle" class="max-h-screen bg-gray-900 h-screen">
  <%= render 'admin_navbar' %>
  <div class="flex">
    <%= render 'dashboard/sidebar' %>
    <%= render 'dashboard/main' %>
  </div>
</div>