config/routes.rb
Rails.application.routes.draw do
  resources :teams
  get "/calender", to: "calender#index"
  get "/search", to: "search#index"
  get "/read_notifications", to: "read_notifications#read_all"
  devise_for :users
  resources :dashboard, only: [:index]
  authenticate :user, ->(user) { user.organisation_owner? } do
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    resources :organisation_users do
      member do
        post "/change_roles", to: "organisation_users#change_role"
      end
    end
  end
  
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
    namespace :admin do
      resources :dashboard
    end
  end

  resources :notifications, only: [:index]
  resources :projects do
    resources :tasks
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/task.rb
class Task < ApplicationRecord
  acts_as_tenant :organisation
  has_many :noticed_events, as: :record, dependent: :destroy, class_name: "Noticed::Event"
  has_many :notifications, through: :noticed_events, class_name: "Noticed::Notification"
  belongs_to :project, touch: true
  belongs_to :assignee, class_name: "User", optional: true

  validates :name, :due_date, presence: true
  validate :due_date_is_futuristic
  validates :name, uniqueness: { case_sensitive: false, scope: :project_id }
  enum :priority, {high: 0, medium:1, low:2 }

  before_update :update_completed_at
  after_update :notify_urgent_task

  scope :incomplete_first, -> { order(completed_at: :desc) }
  scope :urgent, -> { where(due_date: (Time.current..24.hours.from_now)).where(completed: false) }
  scope :completed, -> { where(completed: true) }
  scope :expired, -> { where("due_date < ? AND completed = ?", Date.current, false) }
  scope :pending, -> { where("due_date > ? AND completed = ?", Date.current, false) }

  # def self.incomplete_first
  #   order(completed_at: :desc)
  # end

  def notify_urgent_task
    UrgentTaskJob.perform_later
  end

  def update_completed_at
    self.completed_at = if completed?
      Time.current
    end
  end

  def urgent?
    (Time.current..24.hours.from_now).cover?(due_date) && !completed
  end

  def due_date_is_futuristic
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "Must Be in Future")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    [
      "completed", "completed_at", "created_at", "due_date", "id", "name", "priority", 
      "project_id", "updated_at"
    ]
  end

  def expired?
    due_date < Date.current && !completed
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :authenticate_owner_or_team_leader!, only: %i[create destroy]
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_project

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: "Task was successfully created." }
      else
        format.html { redirect_to project_path(@project), alert: @task.errors.full_messages.join(",") }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_path(@project), notice: "Task was successfully updated." }
      else
        format.html { redirect_to project_path(@project), alert: @task.errors.full_messages.join(",") }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    pp @task
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: "Task was successfully destroyed." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :due_date, :completed_at, :priority, :project_id, :completed, :assignee_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
    def task_priority(priority)
        case priority
        when "high"
            content_tag(:span, "High", class: "leading-5 inline-flex font-bold px-2 rounded-full bg-green-700")
        when "medium"
            content_tag(:span, "Medium", class: "leading-5 inline-flex font-bold px-2 rounded-full bg-yellow-700")
        when "low"
            content_tag(:span, "Low", class: "leading-5 inline-flex font-bold px-2 rounded-full bg-red-700")
        end
    end
end

app/views/tasks/_form.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="relative text-gray-500">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
    <div class="fixed inset-0 bg-gray-800 mt-8 p-8 w-96 h-fit mx-auto">
      <%= form_with(model: [project, task], class: "contents") do |form| %>
        <% if task.errors.any? %>
          <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
            <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
            <ul>
              <% task.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="my-5 text-gray-300">
          <%= form.label :name %>
          <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <div class="my-5">
          <%= form.label :due_date %>
          <%= form.date_field :due_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <div class="my-5">
          <%= form.label :priority %>
          <%= form.select :priority, Task.priorities.keys, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <%= if current_user.organisation_owner || current_user.has_role?(:team_leader) %>
          <div class="my-5 text-gray-300">
            <%= form.label :assign_to %>
            <%= form.collection_select :assignee_id, @project.team.users, :id, :email, include_blank: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
          </div>
        <% end %>
        <div class="inline">
          <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: {turbo_frame: "_top"} %>
          <div class="absolute right-0 top-0">
            <%= link_to project_path(@project) do %>
              <%= inline_svg_tag("close.svg", class: "text-gray-500 hover:text-gray-200" ) %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/_search.html.erb
<div class="p-2 flex justify-between">
    <%= search_form_for @q, url: project_path(@project) do |f| %>
        <div class="flex">
            <%= f.search_field :name_cont, class: "rounded-md text-xs", placeholder: "Search Task Name" %>
            <button type="submit" class="cursor-pointer text-gray-300">
                <%= inline_svg_tag("search.svg") %>
            </button>
        </div>
    <% end %>
    <div>
        <%= link_to "Clear", project_path(@project), class: "font-bold hover:text-gray-300" %>
    </div>
    <%= search_form_for @q, url: project_path(@project) do |f| %>
        <%= f.select :priority_eq, Task.priorities, {}, {onchange: "this.form.requestSubmit()"} %>
    <% end %>
</div>

app/views/tasks/_task.html.erb
<div class="w-full mt-4 text-gray-200">
  <table class="bg-gray-800 rounded-md w-full text-xs">
    <thead>
      <tr class="text-left capitalize border-b border-gray-500">
        <th class="px-4 py-3">Complete</th>
        <th class="px-4 py-3">Completed In</th>
        <th class="px-4 py-3">Assigned To</th>
        <th class="px-4 py-3"><%= sort_link(@q, :name) %></th>
        <th class="px-4 py-3">Priority</th>
        <th class="px-4 py-3"><%= sort_link(@q, :due_date, "Due In") %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr class="border-b border-gray-500 capitalize <%= "line-through text-orange-600" if task.completed?%>">
          <td class="px-4 py-3">
            <%= form_with model: [@project, task] do |form| %>
              <%= form.check_box :completed, class: "cursor-pointer", onchange: "this.form.requestSubmit()" %>
            <% end %>
          </td>
          <td class="px-4 py-3"><%= task.completed? ? "#{time_ago_in_words(task.completed_at)} ago" : "Incomplete" %></td>
          <td class="px-4 py-3"><%= task.assignee&.email %></td>
          <td class="px-4 py-3"><%= task.name %></td>
          <td class="px-4 py-3"><%= task_priority(task.priority) %></td>
          <td class="px-4 py-3"><%= task.expired? ? "Expired" : distance_of_time_in_words(Time.current, task.due_date) %></td>
          <td class="py-3">
            <%= link_to edit_project_task_path(@project, task), data: {turbo: true, turbo_frame: :modal} do %>
              <%= inline_svg_tag("edit.svg") %>
            <% end %>
          </td>
          <td class="py-3">
            <%= button_to project_task_path(@project, task), method: :delete, data: {turbo_confirm: ("Are you Sure?")} do %>
              <%= inline_svg_tag("delete.svg") %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="p-4 flex justify-center">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing task</h1>

  <%= render "form", task: @task, project: @project %>
</div>

app/views/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full p-8">
  <h1 class="font-bold text-4xl">New task</h1>

  <%= render "form", task: @task, project: @project %>
</div>