config/routes.rb
Rails.application.routes.draw do
  resources :teams
  get "/calender", to: "calender#index"
  get "/search", to: "search#index"
  get "/read_notifications", to: "read_notifications#read_all"
  devise_for :users
  resources :dashboard, only: [:index]
  authenticate :user, ->(user) { user.organisation_owner? } do
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    resources :organisation_users do
      member do
        post "/change_roles", to: "organisation_users#change_role"
      end
    end
  end
  
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
    namespace :admin do
      resources :dashboard
    end
  end

  resources :notifications, only: [:index]
  resources :projects do
    resources :tasks
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<div class="w-96 p-6 mx-auto">
  <div class="flex justify-between p-2">
    <h1 class="font-bold text-gray-300">Notifications</h1>
    <div class="text-blue-500">
      <%= link_to "Mark as all read", read_notifications_path %>
    </div>
  </div>
  <div class="p-4 rounded-lg bg-gray-400 max-h-96 overflow-y-scroll">
    <% @notifications.unread.each do |notification| %>
      <li class="mb-6 border-b border-gray-900">
        <%= link_to notification.message, notification.url %>
      </li>
    <% end %>
    <% if @notifications.unread.empty? %>
      <div class="p-4">You have no new notifications</div>
    <% end %>
  </div>
</div>