config/routes.rb
Rails.application.routes.draw do
  resources :teams
  get "/calender", to: "calender#index"
  get "/search", to: "search#index"
  get "/read_notifications", to: "read_notifications#read_all"
  devise_for :users
  resources :dashboard, only: [:index]
  authenticate :user, ->(user) { user.organisation_owner? } do
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    resources :organisation_users do
      member do
        post "/change_roles", to: "organisation_users#change_role"
      end
    end
  end
  
  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
    namespace :admin do
      resources :dashboard
    end
  end

  resources :notifications, only: [:index]
  resources :projects do
    resources :tasks
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :organisation
  belongs_to :team, optional: true
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, uniqueness: {scope: :organisation_id, case_sensitive: false}
  broadcasts_refreshes
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :authenticate_owner!, only: %i[create edit update destroy]
  before_action :set_project, only: [:destroy, :edit, :update, :show]

  def index
    if current_user.organisation_owner?
      @pagy, @projects = pagy(Project.includes(:tasks), limit: 5)
    else
      @pagy, @projects = pagy(current_user.projects.includes(:tasks), limit: 5)
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: "Project Created..!!"
    else
      redirect_to projects_path, alert: @project.errors.full_messages.join(",")
    end
  end

  def destroy
    @project.destroy!
    redirect_to projects_path, notice: "Project Deleted"
  end

  def edit
  end

  def show
    @q = @project.tasks.ransack(params[:q])
    if current_user.organisation_owner? || current_user.has_role?(:team_leader)
      @pagy, @tasks = pagy(@q.result.incomplete_first, limit: 5)
    else
      @pagy, @tasks = pagy(@q.result.incomplete_first.where(assignee: current_user), limit: 5)
    end
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to projects_path, notice: "Project Updated..!!"
    else
      redirect_to projects_path, alert: @project.errors.full_messages.join(",")
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :team_id)
  end

  def set_project
    @project = if current_user.organisation_owner?
        Project.find(params[:id])
      else
        current_user.project.find(params[:id])
      end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_project_form.html.erb
<div class="max-w-sm border-b border-blue-500 pb-1 mx-auto">
    <%= form_with model: Project.new do |form| %>
        <div class="flex">
            <%= form.text_field :name, class: "bg-transparent border-none w-full text-gray-200", placeholder: "Add Project Name" %>
            <%= form.submit "Create", class: "bg-blue-500 p-3 cursor-pointer rounded-md hover:bg-blue-600" %>
        </div>
    <% end %>
</div>

app/views/projects/edit.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="relative">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
    <div class="fixed inset-0 bg-gray-800 mt-8 p-8 size-96 mx-auto">
      <%= form_with model: @project do |form| %>
        <div class="flex flex-col items-center">
          <div class="mb-4">
            <%= form.label :project_name, class: "text-gray-300" %>
            <%= form.text_field :name, class: "rounded-md mb-4 p-3 bg-gray-900 border-none text-gray-200 w-full", placeholder: "Add Project Name" %>
          </div>
          <div class="mb-4">
            <%= form.label :assign_to_team, class: "text-gray-300" %>
            <%= form.collection_select :team_id, Team.all, :id, :name, class: "rounded-md mb-4 p-3 bg-gray-900 border-none text-gray-200 w-full", placeholder: "Add Project Name" %>
          </div>
          <%= form.submit "Update", class: "bg-blue-500 p-3 cursor-pointer rounded-md hover:bg-blue-600 w-full", data: {turbo_frame: "_top"} %>
          <div class="absolute right-0 top-0">
            <%= button_to project_path do %>
              <%= inline_svg_tag("close.svg", class: "text-gray-500 hover:text-gray-200" ) %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <%= turbo_stream_from project %>
<% end %>
<div class="text-gray-200 p-4 w-full">
  <%= render 'add_project_form' %>
  <div class="w-full mt-4">
    <table class="bg-gray-800 rounded-md w-full">
      <thead>
        <tr class="text-left uppercase border-b border-gray-500">
          <th class="px-4 py-3">Name</th>
          <th class="px-4 py-3">Team</th>
          <th class="px-4 py-3">Status</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr class="border-b border-gray-500">
            <td class="px-4 py-3"><%= project.name %></td>
            <td class="px-4 py-3"><%= project.team&.name %></td>
            <td class="px-4 py-3"><%= project.tasks.completed.size %> / <%= project.tasks.size %></td>
            <td class="py-3">
              <%= link_to edit_project_path(project), data: {turbo: true, turbo_frame: :modal} do %>
                <%= inline_svg_tag("edit.svg") %>
              <% end %>
            </td>
            <td class="py-3">
              <%= link_to project_path(project) do %>
                <%= inline_svg_tag("show.svg") %>
              <% end %>
            </td>
            <td class="py-3">
              <%= button_to project_path(project), method: :delete, data: {turbo_confirm: ("Are you Sure?")} do %>
                <%= inline_svg_tag("delete.svg") %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="p-4 flex justify-center">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%= turbo_stream_from @project %>
<div class="w-full p-8 text-gray-500">
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl"><%= @project.name %></h1>
      <%= link_to "New task", new_project_task_path(@project), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium", data: {turbo: true, turbo_frame: :modal} %>
    </div>
    <progress class="w-full mt-4" value="<%= @project.tasks.completed.count %>" max="<%= @project.tasks.count %>"></progress>
    <%= render 'tasks/search' %>
    <%= render 'tasks/task' %>
</div>
  